// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHvRZWDOUbl2fPxUzh21PP14t6p5TShkI',
    appId: '1:341362410174:web:771c3b42a49c07336894ef',
    messagingSenderId: '341362410174',
    projectId: 'pro-a12202206882',
    authDomain: 'pro-a12202206882.firebaseapp.com',
    storageBucket: 'pro-a12202206882.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQw64k6N_CAY0aPkvowypcc3zhZAcat18',
    appId: '1:341362410174:android:76671372060dd0086894ef',
    messagingSenderId: '341362410174',
    projectId: 'pro-a12202206882',
    storageBucket: 'pro-a12202206882.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHvRZWDOUbl2fPxUzh21PP14t6p5TShkI',
    appId: '1:341362410174:web:5bc58db4454902f96894ef',
    messagingSenderId: '341362410174',
    projectId: 'pro-a12202206882',
    authDomain: 'pro-a12202206882.firebaseapp.com',
    storageBucket: 'pro-a12202206882.appspot.com',
  );
}
